# AUTOGENERATED! DO NOT EDIT! File to edit: ../j02_AGEN_LearningDynamics.ipynb.

# %% auto 0
__all__ = ['make_variable_vector', 'LearningAgents', 'random_softmax_policy', 'zero_intelligence_policy', 'update', 'Rioa',
           'Yisa', 'Bios', 'Ps', 'Tss', 'compute_stationarydistribution', 'trajectory', 'Ri', 'obsdist', 'Tioo', 'id',
           'ModelFreeAgents']

# %% ../j02_AGEN_LearningDynamics.ipynb 3
import jax
import numpy as np
import jax.numpy as jnp
from jax import jit
from functools import partial
import itertools as it

# %% ../j02_AGEN_LearningDynamics.ipynb 5
def make_variable_vector(variable,  # can be iterable or float or int
                         length:int  # length of the vector
                        ):  # vector
    "Turn a `variable` into a vector or check that `length` is consistent."
    if hasattr(variable, '__iter__'):
        assert len(variable) == length, 'Wrong number given'
        return jnp.array(variable)
    else:
        return jnp.repeat(variable, length)

# %% ../j02_AGEN_LearningDynamics.ipynb 8
class LearningAgents:
    
    def __init__(self,
                 env,
                 learning_rates,
                 discount_factors=None, # dummy argument for compatibility
                 choice_intensities=None, # dummy argument for compatibility
                 use_prefactor=None # dummy argument for compatibility
                ):
        
        self.env = env
        TransitionTensor = env.T
        RewardTensor = env.R
        ObservationTensor = env.O
    
        R = jnp.array(RewardTensor)
        T = jnp.array(TransitionTensor)
        O = jnp.array(ObservationTensor)
        
        # number of agents
        NrAgt = R.shape[0]  
        assert len(T.shape[1:-1]) == NrAgt, "Inconsistent number of agents"
        assert len(R.shape[2:-1]) == NrAgt, "Inconsistent number of agents"
        assert O.shape[0] == NrAgt, "Inconsistent number of agents"

        # number of actions for each agent        
        NrAct = T.shape[1] 
        assert np.allclose(T.shape[1:-1], NrAct), 'Inconsistent number of actions'
        assert np.allclose(R.shape[2:-1], NrAct), 'Inconsistent number of actions'
        
        # number of states
        NrSts = T.shape[0] 
        assert T.shape[-1] == NrSts, 'Inconsistent number of states'
        assert R.shape[-1] == NrSts, 'Inconsistent number of states'
        assert R.shape[1] == NrSts, 'Inconsistent number of states'
        assert O.shape[1] == NrSts, 'Inconsistent number of states'
        
        # number of observations
        NrObs = O.shape[-1]   

        self.R, self.T, self.O = R, T, O
        self.NrAgt, self.NrAct, self.NrSts, self.NrObs = NrAgt, NrAct, NrSts, NrObs
        self.N, self.M, self.Z, self.Q = NrAgt, NrAct, NrSts, NrObs
        
        self.learning_rates = make_variable_vector(learning_rates, NrAgt)
        
        # state and obs distribution helpers
        self.Omega = self._OtherAgentsActionsSummationTensor()
        self.has_last_statdist = False
        self._last_statedist = jnp.ones(NrSts) / NrSts
        self.has_last_obsdist = False
        self._last_obsdist = jnp.ones((NrAgt, NrObs)) / NrObs

# %% ../j02_AGEN_LearningDynamics.ipynb 10
def random_softmax_policy(self:LearningAgents):
    """Softmax policy with random probabilities."""
    expQ = jnp.exp(np.random.randn(self.NrAgt, self.NrObs, self.NrAct))
    return expQ / expQ.sum(axis=-1, keepdims=True)

LearningAgents.random_softmax_policy = random_softmax_policy

# %% ../j02_AGEN_LearningDynamics.ipynb 12
def zero_intelligence_policy(self:LearningAgents):
    """Policy with equal probabilities."""
    return jnp.ones((self.NrAgt, self.NrObs, self.NrAct)) / float(self.NrAct)
LearningAgents.zero_intelligence_policy = zero_intelligence_policy

# %% ../j02_AGEN_LearningDynamics.ipynb 15
@partial(jit, static_argnums=0)
def update(self: LearningAgents,
           Xioa # Joint strategy
          ) -> tuple:  # (Updated joint strategy, Prediction error)
    """
    Performs a learning update of the joint behavioral rule,
    given joint behavior `Xioa`.
    """
    Rioa = self.Rioa(Xioa)
    n = jnp.newaxis
    XexpaRioa = Xioa * jnp.exp(self.learning_rates[:,n,n] * Rioa)
    Xioa_ = XexpaRioa / XexpaRioa.sum(-1, keepdims=True)
    return Xioa_

LearningAgents.update = update

# %% ../j02_AGEN_LearningDynamics.ipynb 18
@partial(jit, static_argnums=0)    
def Rioa(self: LearningAgents, 
        Xioa, 
        Bios=None, 
        Yisa=None):
    """Compute average reward Riosa, given joint policy X """
    # For speed up
    Bios = self.Bios(Xioa) if Bios is None else Bios
    Yisa = self.Yisa(Xioa) if Yisa is None else Yisa
    
    # Variables
    # agent i, act a, state s, next state s_, observation o
    i = 0; a = 1; s = 2; s_ = 3; o = 4
    j2k = list(range(5, 5+self.NrAgt-1))  # other agents
    b2d = list(range(5+self.NrAgt-1, 5+self.NrAgt-1 + self.NrAgt))  # all actions
    e2f = list(range(4+2*self.NrAgt, 4+2*self.NrAgt + self.NrAgt-1))  # all other acts

    sumsis = [[j2k[l], s, e2f[l]] for l in range(self.NrAgt-1)]  # sum inds
    otherY = list(it.chain(*zip((self.NrAgt-1)*[Yisa], sumsis)))
    args = [self.Omega, [i]+j2k+[a]+b2d+e2f, Bios, [i, o, s]] +\
            otherY + [self.T, [s]+b2d+[s_], self.R, [i, s]+b2d+[s_],
            [i, o, a]]

    return jnp.einsum(*args, optimize=True)

LearningAgents.Rioa = Rioa

# %% ../j02_AGEN_LearningDynamics.ipynb 20
@partial(jit, static_argnums=0)    
def Yisa(self: LearningAgents, 
         Xioa):
    """
    Compute state-action policy given the current observation-action policy
    """
    i = 0; a = 1; s = 2; o = 4  # variables
    args = [self.O, [i, s, o], Xioa, [i, o, a], [i, s, a]]
    Yisa = jnp.einsum(*args, optimize=True)

    return Yisa         

LearningAgents.Yisa = Yisa  

# %% ../j02_AGEN_LearningDynamics.ipynb 23
@partial(jit, static_argnums=0)
def Bios(self: LearningAgents,
         Xioa):
    """
    Compute 'belief' that environment is in stats s given agent i
    observes observation o (Bayes Rule)
    
    Unsafe when stationary state distribution is not unique
    (i.e., when policies are too extreme)
    """
    i, s, o = 0, 1, 2 # variables 
    # pS = self.statedist(X) # from full obs base (requires Tss from above)
    pS = self.Ps(Xioa, self._last_statedist)
    self._last_statedist = pS
    self.has_last_statdist = True

    b = jnp.einsum(self.O, [i,s,o], pS, [s], [i,s,o], optimize=True)
    bsum = b.sum(axis=1, keepdims=True)
    bsum = bsum + (bsum == 0)  # to avoid dividing by zero
    Biso = b / bsum
    Bios = jnp.swapaxes(Biso, 1,-1)
    
    return Bios

LearningAgents.Bios = Bios

# %% ../j02_AGEN_LearningDynamics.ipynb 25
@partial(jit, static_argnums=0)  
def Ps(self,
       Xioa,  # Joint strategy
       pS0):  # Last stationary state distribution 
    """
    Compute stationary state distribution `Ps`, given joint strategy `Xioa`
    using JAX.
    """
    Tss = self.Tss(Xioa)
    _pS = compute_stationarydistribution(Tss)
    nrS = jnp.where(_pS.mean(0)!=-10, 1, 0).sum()

    @jit
    def single_dist(pS):
        return jnp.max(jnp.where(_pS.mean(0)!=-10,
                                 jnp.arange(_pS.shape[0]), -1))
    @jit
    def multi_dist(pS):
        ix = jnp.argmin(jnp.linalg.norm(_pS.T - pS0, axis=-1))
        return ix
        
    ix = jax.lax.cond(nrS == 1, single_dist, multi_dist, _pS)

    pS = _pS[:, ix]
    return pS

LearningAgents.Ps = Ps

# %% ../j02_AGEN_LearningDynamics.ipynb 28
@partial(jit, static_argnums=0)
def Tss(self: LearningAgents,
        Xioa):
    """Compute average transition model Tss given policy X"""
    Yisa = self.Yisa(Xioa)

    s = 1  # state s
    sprim = 2  # next state s'
    b2d = list(range(3, 3+self.NrAgt))  # all actions

    X4einsum = list(it.chain(*zip(Yisa, [[s, b2d[a]]
                                         for a in range(self.NrAgt)])))
    args = X4einsum + [self.T, [s]+b2d+[sprim], [s, sprim]]
    return jnp.einsum(*args, optimize=True)

LearningAgents.Tss = Tss

# %% ../j02_AGEN_LearningDynamics.ipynb 32
@jit
def compute_stationarydistribution(Tkk:jnp.ndarray):  # Transition matrix
    """Compute stationary distribution for transition matrix `Tkk`."""
    # eigenvectors
    oeival, oeivec = jnp.linalg.eig(Tkk.T)
    oeival = oeival.real
    oeivec = oeivec.real
    
    get_mask = lambda tol: jnp.abs(oeival - 1) < tol
  
    tolerances = jax.lax.map(lambda x: 0.1**x, jnp.arange(1,16,1))
    masks = jax.lax.map(get_mask, tolerances)
    ix = jnp.max(jnp.where(masks.sum(-1)>=1, jnp.arange(len(masks)), -1))
    mask = masks[ix]
    tol = tolerances[ix]
    
    # obtain stationary distribution
    meivec = jnp.where(mask, oeivec, -42)
    
    dist = meivec / meivec.sum(axis=0, keepdims=True)
    dist = jnp.where(dist < tol, 0, dist)
    dist = dist / dist.sum(axis=0, keepdims=True)
    
    return jnp.where(meivec==-42, -10, dist)

# %% ../j02_AGEN_LearningDynamics.ipynb 35
def _OtherAgentsActionsSummationTensor(self:LearningAgents):
    """
    To sum over the other agents and their respective actions using `einsum`.
    """
    dim = np.concatenate(([self.NrAgt],  # agent i
                          [self.NrAgt for _ in range(self.NrAgt-1)],  # other agnt
                          [self.NrAct],  # agent a of agent i
                          [self.NrAct for _ in range(self.NrAgt)],  # all acts
                          [self.NrAct for _ in range(self.NrAgt-1)]))  # other a's
    Omega = np.zeros(dim.astype(int), int)

    for index, _ in np.ndenumerate(Omega):
        I = index[0]
        notI = index[1:self.NrAgt]
        A = index[self.NrAgt]
        allA = index[self.NrAgt+1:2*self.NrAgt+1]
        notA = index[2*self.NrAgt+1:]

        if len(np.unique(np.concatenate(([I], notI)))) is self.NrAgt:
            # all agents indices are different

            if A == allA[I]:
                # action of agent i equals some other action
                cd = allA[:I] + allA[I+1:]  # other actionss
                areequal = [cd[k] == notA[k] for k in range(self.NrAgt-1)]
                if np.all(areequal):
                    Omega[index] = 1

    return jnp.array(Omega)
LearningAgents._OtherAgentsActionsSummationTensor = _OtherAgentsActionsSummationTensor

# %% ../j02_AGEN_LearningDynamics.ipynb 38
def trajectory(self: LearningAgents,
               Xinit:jnp.ndarray,  # Initial condition
               Tmax:int=100, # the maximum number of iteration steps
               tolerance:float=None, # to determine if a fix point is reached 
               verbose=False,  # Say something during computation?
               **kwargs) -> tuple: # (`trajectory`, `fixpointreached`)
    """
    Compute a joint learning trajectory.
    """
    traj = []
    t = 0
    X = Xinit.copy()
    fixpreached = False

    while not fixpreached and t < Tmax:
        print(f"\r [computing trajectory] step {t}", end='') if verbose else None 
        traj.append(X)

        X_ = self.update(X)
        if np.any(np.isnan(X_)):
            fixpreached = True
            break

        if tolerance is not None:
            fixpreached = np.linalg.norm(X_ - X) < tolerance

        X = X_
        t += 1

    print(f" [trajectory computed]") if verbose else None

    return np.array(traj), fixpreached
LearningAgents.trajectory = trajectory

# %% ../j02_AGEN_LearningDynamics.ipynb 41
# @partial(jit, static_argnums=0)
def Ri(self: LearningAgents, 
       Xioa):
    """Compute average reward Ri, given joint policy X""" 
    i, o, a = 0, 1, 2
    return jnp.einsum(self.obsdist(Xioa), [i, o], 
                      Xioa, [i, o, a],
                      self.Rioa(Xioa), [i, o, a], [i])
LearningAgents.Ri = Ri

# %% ../j02_AGEN_LearningDynamics.ipynb 45
# @partial(jit, static_argnums=0)
def obsdist(self: LearningAgents, Xioa):
    """Compute stationary distribution, given joint policy X"""
    Tioo = self.Tioo(Xioa)
    Dio = np.zeros((self.NrAgt, self.NrObs))
    
    for i in range(self.NrAgt):
        pO = np.array(compute_stationarydistribution(Tioo[i]))
    
        pO = pO[:, pO.mean(0)!=-10]
        if len(pO[0]) == 0:  # this happens when the tollerance can distin.
            assert False, 'No _statdist return - must not happen'
        elif len(pO[0]) > 1:  # Should not happen, in an ideal world
            # sidenote: This means an ideal world is ergodic ;)
            print("More than 1 state-eigenvector found")
            print(pO.round(2))
            nr = len(pO[0])
            choice = np.random.randint(nr)
            print("taking random one: ", choice)
            pO = pO[:, choice]
                    
        Dio[i] = pO.flatten()

    self._last_obsdist = Dio
    self.has_last_obsdist = True
    return Dio
LearningAgents.obsdist = obsdist

# %% ../j02_AGEN_LearningDynamics.ipynb 48
@partial(jit, static_argnums=0)    
def Tioo(self, X, Bios=None, Yisa=None):
    """Compute average transition model Tioo, given joint policy X"""
    # For speed up
    Bios = self.Bios(X) if Bios is None else Bios
    Yisa = self.Yisa(X) if Yisa is None else Yisa
    
    # variables 
    # agent i, state s, next state s_, observation o, next obs o', all acts
    i = 0; s = 1; s_ = 2; o = 3; o_ = 4; b2d = list(range(5, 5+self.NrAgt)) 

    Y4einsum = list(it.chain(*zip(Yisa, 
                                  [[s, b2d[a]] for a in range(self.NrAgt)])))
    
    args = [Bios, [i, o, s]] + Y4einsum + [self.T, [s]+b2d+[s_],
            self.O, [i, s_, o_], [i, o, o_]]
    return jnp.einsum(*args, optimize=True)
LearningAgents.Tioo = Tioo

# %% ../j02_AGEN_LearningDynamics.ipynb 51
def id(self: LearningAgents
       ) -> str:  # id
    """Returns an identifier to handle simulation runs."""
    envid = self.env.id() + "__"
    agentsid = f"j{self.__class__.__name__}_"

    agentsid += 'PartObs_'        

    agentsid += f"{str(self.learning_rates)}"
    
    return envid + agentsid
LearningAgents.id = id

# %% ../j02_AGEN_LearningDynamics.ipynb 54
class ModelFreeAgents(LearningAgents):
    
     # @partial(jit, static_argnums=0)
     def update(self,
                Xioa # Joint strategy
               ) -> tuple:  # (Updated joint strategy, Prediction error)
          """
          Performs a learning update of the joint behavioral rule,
          given joint behavior `Xioa`.
          """
          Rioa = self.Rioa(Xioa)
          Pio = self.obsdist(Xioa)

          n = jnp.newaxis
          XexpaRioa = Xioa * jnp.exp(self.learning_rates[:,n,n]
                                     * Pio[:,:,n]
                                     * Xioa
                                     * Rioa)
          Xioa_ = XexpaRioa / XexpaRioa.sum(-1, keepdims=True)
          return Xioa_

          LearningAgents.update = update
