# AUTOGENERATED! DO NOT EDIT! File to edit: ../j82_AUX_ObtainResultsData.ipynb.

# %% auto 0
__all__ = ['lowlevel_datadictionary', 'highlevel_datadictionary', 'noise_levels', 'ddirs', 'mobaparams', 'mofeparams',
           'obtain_all_noise_variation_comparisons']

# %% ../j82_AUX_ObtainResultsData.ipynb 3
# import numpy as np
from .LearningDynamics import LearningAgents, ModelFreeAgents
from .SimulationScripts import create_consistent_linspace
from .SimulationScripts import obtain_noise_variation_comparison


# %% ../j82_AUX_ObtainResultsData.ipynb 4
lowlevel_datadictionary = "/Users/wolf/Downloads/L2SocialData"
highlevel_datadictionary = "./_data"

# %% ../j82_AUX_ObtainResultsData.ipynb 5
noise_levels = create_consistent_linspace(0.01, 4.0, 81)
noise_levels

# %% ../j82_AUX_ObtainResultsData.ipynb 6
ddirs = dict(lowlevel_ddir=lowlevel_datadictionary,
             highlevel_ddir=highlevel_datadictionary)

mobaparams = dict(agentclass=LearningAgents, maxT=5000, number_of_initial_policies_k=25)
mofeparams = dict(agentclass=ModelFreeAgents, maxT=250000, number_of_initial_policies_k=10)

# %% ../j82_AUX_ObtainResultsData.ipynb 8
def obtain_all_noise_variation_comparisons():
    NoiVar_MBA_pAhigh = obtain_noise_variation_comparison(
        probabilityA=0.5, 
        noise_levels=noise_levels,
        **mobaparams, **ddirs)

    NoiVar_MFA_pAhigh = obtain_noise_variation_comparison(
        probabilityA=0.5, 
        noise_levels=noise_levels,
        **mofeparams, **ddirs)

    NoiVar_MBA_pAmid = obtain_noise_variation_comparison(
        probabilityA=0.58, 
        noise_levels=noise_levels,
        **mobaparams, **ddirs)

    NoiVar_MFA_pAmid = obtain_noise_variation_comparison(
        probabilityA=0.58, 
        noise_levels=noise_levels,
        **mofeparams, **ddirs)

    NoiVar_MBA_pAlow = obtain_noise_variation_comparison(
        probabilityA=0.7, 
        noise_levels=noise_levels,
        **mobaparams, **ddirs)

    NoiVar_MFA_pAlow = obtain_noise_variation_comparison(
        probabilityA=0.7, 
        noise_levels=noise_levels,
        **mofeparams, **ddirs)
    
    return (NoiVar_MBA_pAhigh, NoiVar_MFA_pAhigh,
            NoiVar_MBA_pAmid, NoiVar_MFA_pAmid,
            NoiVar_MBA_pAlow, NoiVar_MFA_pAlow)
