# AUTOGENERATED! DO NOT EDIT! File to edit: ../j81_AUX_Simulation.ipynb.

# %% auto 0
__all__ = ['create_consistent_linspace', 'collective_intelligence', 'create_inital_lhs', 'compute_trajectories', 'check_run',
           'obtain_trajectories', 'final_policies_Xkioa', 'final_rewards_Rki', 'compute_noise_variation',
           'dict_to_string', 'obtain_noise_variation', 'obtain_noise_variation_comparison']

# %% ../j81_AUX_Simulation.ipynb 3
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

from .UncertainDecisionProblem import \
    SingleAgentUncertainDecisionProblem, TwoAgentUncertainDecisionProblem
from .LearningDynamics import LearningAgents

from skopt.sampler import Lhs
from skopt.space import Space

import hashlib
from collections import namedtuple

# %% ../j81_AUX_Simulation.ipynb 5
def create_consistent_linspace(start, stop, number, decimals=8):
    return np.round(np.linspace(start, stop, number, dtype=np.float64), decimals)

# %% ../j81_AUX_Simulation.ipynb 8
def collective_intelligence(multiagent_reward, 
                            singleagent_reward):
    return (multiagent_reward - singleagent_reward) / singleagent_reward

# %% ../j81_AUX_Simulation.ipynb 11
def create_inital_lhs(maei, # multiagent environment interface
                      number, # number of initial policies to generate
                      iterations=1000,  # number of interations used for latin hypercube sampling
                      seed=42): # seed for random number generator
    """
    Returns near random samples of initial policies
    """
    assert maei.M == 2, 'Sampling for M>2 not straightforward'
    # https://www.egr.msu.edu/~kdeb/papers/c2018010.pdf
    # https://www.cs.cmu.edu/~nasmith/papers/smith+tromble.tr04.pdf
    
    eps = 10**(-6)
    space = Space(maei.N * maei.Q * (maei.M-1)*[(0.0+eps, 1.0-eps)])
    
    # generate latin hyper cubes
    lhs = Lhs(criterion="maximin", iterations=iterations)
    x = lhs.generate(space.dimensions, number, random_state=seed)
    x = np.array(x).reshape(number, maei.N, maei.Q, maei.M-1)
    
    # complete and normalize
    inits = np.zeros((number, maei.N, maei.Q, maei.M))
    inits[..., 0] = x[...,0]
    inits[..., 1] = 1 - x[...,0]
    
    return inits

# %% ../j81_AUX_Simulation.ipynb 18
def compute_trajectories(maei,        # multiagent environment interface
                         inits,       # initial policies
                         maxT=1000,   # maximal number of learning steps
                         tolerance=10e-7): # tolerance for convergence
    """
    Returns array of policy trajectories for different initial policies and 
    array of whether they converged
    """
    trjs = []; fprs = []
    leni = len(inits)
    
    for xi, x0 in enumerate(inits):
        print("\r [Computing policy trajectories]:",
              np.round(xi/leni, 4), end='')
        x = x0.copy()
        
        trj, fpr = maei.trajectory(x, Tmax=maxT, tolerance=tolerance)
        
        trjs.append(trj.astype(np.float32))
        fprs.append(fpr)
    
    print("")
    return np.array(trjs, dtype=object), np.array(fprs)

# %% ../j81_AUX_Simulation.ipynb 22
def check_run(trjs, fprs=None):
    """
    plots histogram of trajectory length after computing
    """
    #if fprs is not None:
        #print('Unique fixed points reached:', np.unique(fprs))
    plt.hist([len(traj) for traj in trjs], bins=20);
    plt.title('Histrogram of trajectories lengths')


# %% ../j81_AUX_Simulation.ipynb 25
def _transform_tensor_into_hash(tens):
    """Transform tens into a string for filename saving"""
    r = int(hashlib.sha512(str(tens).encode('utf-8')).hexdigest()[:16], 16)
    return r

# %% ../j81_AUX_Simulation.ipynb 29
def obtain_trajectories(maei,  # multiagent environment interface
                        initXkioa,  # initial policies
                        verbose=True,  # indicates if explanations should be printed
                        maxT=5000,  # maximal number of learning steps
                        ddir='data'):  # directory where to save data
    """
    Loads or computes and saves learning trajectories.
    """
    fn = ddir + '/TRAJECTORIES_' + maei.id() + '_'\
        + str(_transform_tensor_into_hash(initXkioa))
    fn += ".npz"
    
    try:
        dat = np.load(fn, allow_pickle=True)
        ddic = dict(zip((k for k in dat), (dat[k] for k in dat)))
        print("Loading ", fn) if verbose else None
    
    except:
        print("Computing ", fn) if verbose else None
        trjs, fprs = compute_trajectories(maei, initXkioa, maxT=maxT)
        check_run(trjs, fprs)
        # rtrajs = obtain_rewards(AEi, πtrajs)§
        
        ddic = dict(trjs=trjs, fprs=fprs)
        np.savez_compressed(fn, **ddic)
        dat = np.load(fn, allow_pickle=True)
        ddic = dict(zip((k for k in dat), (dat[k] for k in dat)))
    
    return ddic['trjs'], ddic['fprs']

# %% ../j81_AUX_Simulation.ipynb 39
def final_policies_Xkioa(Xktioa):
    return np.array([Xtioa[-1] for Xtioa in Xktioa])

# %% ../j81_AUX_Simulation.ipynb 43
def final_rewards_Rki(maei,  # multiagent environment interface
                      Xktioa): # learning trajectories
    """
    Returns the rewards `Rki` that agents receive at the end of the learning 
    trajectories `Xktioa`.
    """
    if not maei.has_last_obsdist:    # to avoid a small bug 
        maei.obsdist(Xktioa[0][-1].astype(np.float32))  # with jax' just-in-time compilation
    
    Rki = []
    for Xtioa in Xktioa:
        Xioa = Xtioa[-1]
        Ri = maei.Ri(Xioa.astype(np.float32))
        Rki.append(Ri)
        
    return np.array(Rki)

# %% ../j81_AUX_Simulation.ipynb 48
def compute_noise_variation(
    envclass,        # environment class
    noises,          # iterable of noise levels
    envparams,       # dictionary of environment parameters
    agentclass,      # agent class
    agentparams,     # dictionary of agent parameters
    initialXkioa,    # initial policies, k indicates index of initial policy
    maxT=5000,       # maximal number of learning steps
    ddir='data'):    # directory to save and load data
    """Computes the learning trajectories for different noise levels.
       Returns the final rewards and convergence times."""
    
    convergence_times_Tnk = []  # n indicates noise index
    final_rewards_Rnki = []   
    final_policies_Xnkioa = []
    
    for noise in noises:
        print(f" = = = = {noise} = = = =")
        env = envclass(noiselevel=noise, **envparams)
        maei = agentclass(env, **agentparams)
        
        Xktioa, FPRk = obtain_trajectories(
            maei, initialXkioa, verbose=True, maxT=maxT, ddir=ddir)

        convergence_times_Tnk.append([len(Xtios) for Xtios in Xktioa])
        final_rewards_Rnki.append(final_rewards_Rki(maei, Xktioa))
        final_policies_Xnkioa.append(final_policies_Xkioa(Xktioa))
        
        
    return (np.array(convergence_times_Tnk),
            np.array(final_rewards_Rnki),
            np.array(final_policies_Xnkioa))

# %% ../j81_AUX_Simulation.ipynb 59
def dict_to_string(paramdic):
    string = ''
    for k, v in paramdic.items():
        string += f'{k}{v}_'
    return string[:-1]

# %% ../j81_AUX_Simulation.ipynb 65
def obtain_noise_variation(
    envclass,        # environment class
    noises,          # iterable of noise levels
    envparams,       # dictionary of environment parameters
    agentclass,      # agent class
    agentparams,     # dictionary of agent parameters
    initialXkioa,    # initial policies, k indicates index of initial policy
    maxT=5000,       # maximal number of learning steps
    lowlevel_ddir='',  # directory to save and load low-level data
    highlevel_ddir='',  # directory to save and load high-level data
    ):
    """Computes the learning trajectories for different noise levels.
       Returns the final rewards and convergence times."""
    
    # Create file name
    fn = highlevel_ddir + '/NOISEVARIATION_' + envclass.__name__ + '_'\
        + dict_to_string(envparams)\
        + '_' + agentclass.__name__ + '_' + dict_to_string(agentparams)\
        + '_' + "initalX" + str(_transform_tensor_into_hash(initialXkioa))\
        + '_' + "maxT" + str(maxT)\
        + '_' + "Noises" + str(_transform_tensor_into_hash(np.array(noises)))\
        + ".npz"
    
    try:
        dat = np.load(fn, allow_pickle=True)
        ddic = dict(zip((k for k in dat), (dat[k] for k in dat)))
        print("Loading noise variation:", fn)

    except:
        print("Computing noise variation:", fn)
        convergence_Tnk, final_Rnki, final_Xnkioa = compute_noise_variation(
            envclass,        # environment class
            noises,          # iterable of noise levels
            envparams,       # dictionary of environment parameters
            agentclass,      # agent class
            agentparams,     # dictionary of agent parameters
            initialXkioa,    # initial policies, k is index of initial policy
            maxT=maxT,       # maximal number of learning steps
            ddir=lowlevel_ddir)
        ddic = dict(convergence_times_Tnk=convergence_Tnk, 
                    final_rewards_Rnki=final_Rnki,
                    final_policies_Xnkioa=final_Xnkioa)
        np.savez_compressed(fn, **ddic)
        dat = np.load(fn, allow_pickle=True)
        ddic = dict(zip((k for k in dat), (dat[k] for k in dat)))
        
    return (ddic['convergence_times_Tnk'],
            ddic['final_rewards_Rnki'],
            ddic['final_policies_Xnkioa'])

# %% ../j81_AUX_Simulation.ipynb 77
def obtain_noise_variation_comparison(lowlevel_ddir, highlevel_ddir,
                                      probabilityA, noise_levels, 
                                      agentclass, maxT,
                                      likelydistance=0.5,
                                      number_of_initial_policies_k=25):
    # Fixed parameters
    agentparams = dict(learning_rates=0.25)
    envparams = dict(probabilityA=probabilityA, likelydistance=likelydistance)

    ## Two-agent model
    envclass = TwoAgentUncertainDecisionProblem
    env = envclass(noiselevel=0.5, **envparams)
    maei = agentclass(env, **agentparams)
    
    if number_of_initial_policies_k == 1:
        initialXkios = np.array([maei.zero_intelligence_policy()])
    else:
        initialXkios = create_inital_lhs(maei, number_of_initial_policies_k)

    twoagent_convergence_Tnk, twoagent_final_Rnki, twoagent_Xnkioa =\
        obtain_noise_variation(
        envclass,        # environment class
        noise_levels,    # iterable of noise levels
        envparams,       # dictionary of environment parameters
        agentclass,      # agent class
        agentparams,     # dictionary of agent parameters
        initialXkios,    # initial policies, k indicates index of initial policy
        maxT=maxT,       # maximal number of learning steps
        lowlevel_ddir=lowlevel_ddir, highlevel_ddir=highlevel_ddir)
        
    # Single-agent model
    envclass = SingleAgentUncertainDecisionProblem
    env = envclass(noiselevel=0.5, **envparams)
    maei = agentclass(env, **agentparams)
    
    if number_of_initial_policies_k == 1:
        initialXkios = np.array([maei.zero_intelligence_policy()])
    else:
        initialXkios = create_inital_lhs(maei, number_of_initial_policies_k)
        
    singleagent_convergence_Tnk, singleagent_final_Rnki, singleagent_Xnkioa =\
        obtain_noise_variation(
        envclass,        # environment class
        noise_levels,    # iterable of noise levels
        envparams,       # dictionary of environment parameters
        agentclass,      # agent class
        agentparams,     # dictionary of agent parameters
        initialXkios,    # initial policies, k indicates index of initial policy
        maxT=maxT,       # maximal number of learning steps
        lowlevel_ddir=lowlevel_ddir, highlevel_ddir=highlevel_ddir)
    
    NoiseVariation = namedtuple('NoiseVariation',
                                ['ta_Tnk', 'ta_Rnki', 'ta_Xnkioa',
                                 'sa_Tnk', 'sa_Rnki', 'sa_Xnkioa'])

    return NoiseVariation(ta_Tnk=twoagent_convergence_Tnk, 
                          ta_Rnki=twoagent_final_Rnki, 
                          ta_Xnkioa=twoagent_Xnkioa,
                          sa_Tnk=singleagent_convergence_Tnk, 
                          sa_Rnki=singleagent_final_Rnki,
                          sa_Xnkioa=singleagent_Xnkioa)
