# AUTOGENERATED! DO NOT EDIT! File to edit: ../j01_ENVI_UncertainDecisionProblem.ipynb.

# %% auto 0
__all__ = ['plot_observation_function', 'probabilities', 'plot_observation_probabilities', 'ebase',
           'SingleAgentUncertainDecisionProblem', 'TwoAgentUncertainDecisionProblem']

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 3
import numpy as np
import itertools as it
from scipy.stats import norm
from fastcore.utils import patch
import matplotlib.pyplot as plt
np.set_printoptions(legacy='1.25')

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 8
def plot_observation_function(noise_level = 1, 
                              distance = 0.5,
                              x_extend = 3):
    x = np.linspace(-x_extend, x_extend, 1000)
    plt.plot(x, norm.pdf(x, loc=0, scale=noise_level), 'k-')

    x1 = np.linspace(-x_extend, -distance, 1000)
    plt.fill_between(x1, norm.pdf(x1, loc=0, scale=noise_level),
                     color='darkgreen', alpha=0.5)

    x2 = np.linspace(-distance, 0.5, 1000)
    plt.fill_between(x2, norm.pdf(x2, loc=0, scale=noise_level),
                     color='lightgreen', alpha=0.5)

    x3 = np.linspace(0.5, 1+distance, 1000)
    plt.fill_between(x3, norm.pdf(x3, loc=0, scale=noise_level),
                     color='violet', alpha=0.5)

    x4 = np.linspace(1+distance, x_extend, 1000)
    plt.fill_between(x4, norm.pdf(x4, loc=0, scale=noise_level),
                     color='purple', alpha=0.5)

    # Get current xticks and labels
    locations, labels = plt.xticks()

    # Create new labels
    new_labels = ['' for _ in labels]
    for i, loc in enumerate(locations):
        if abs(loc - 0) < 1e-2: new_labels[i] = 'A'
        elif abs(loc - 1) < 1e-2: new_labels[i] = 'B'

    # Set new labels
    plt.xticks(locations, new_labels)
    plt.gca().spines[['top', 'right']].set_visible(False)
    plt.xlim(-x_extend, x_extend)

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 12
def probabilities(noiselevel, likelydistance):
    """
    Returns observation probabilities. 
    """
    pVeryLikelyTrue = norm.cdf(-likelydistance, 0,  noiselevel)        # A
    pLikelyTrue = norm.cdf(0.5, 0, noiselevel) - pVeryLikelyTrue       # a  
    pLikelyWrong = norm.cdf(1+likelydistance, 0, noiselevel)\
        - norm.cdf(0.5, 0, noiselevel)                                 # b
    pVeryLikelyWrong = 1 -  norm.cdf(1+likelydistance, 0, noiselevel)  # B
    
    return [pVeryLikelyTrue, pLikelyTrue, pLikelyWrong, pVeryLikelyWrong]

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 15
def plot_observation_probabilities(max_noiselevel, likelydistance=0.5):
    noiselevels = np.linspace(0.01, max_noiselevel, 200)
    probs = np.array([probabilities(sig, likelydistance) for sig in noiselevels])
    plt.plot(noiselevels, probs[:,0], '.-', label= 'A', color = 'darkgreen')
    plt.plot(noiselevels, probs[:,1], '.-', label= 'a', color = 'lightgreen')
    plt.plot(noiselevels, probs[:,2], '.-', label= 'b', color = 'violet')
    plt.plot(noiselevels, probs[:,3], '.-', label= 'B', color = 'purple')
    
    plt.plot(noiselevels, probs[:,0]+probs[:,1], '--', label= 'A+a', color = 'green')
    plt.plot(noiselevels, probs[:,2]+probs[:,3], '--', label= 'B+b', color = 'pink')

    plt.xlabel('Observational uncertainty $\\sigma$')
    plt.ylabel('Observation probabilities')
    plt.legend()

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 19
class ebase(object):
    """Base environment. All environments should inherit from this one."""
    
    def __init__(self):
               
        self.T = self.TransitionTensor()
        self.R = self.RewardTensor()
        self.O = self.ObservationTensor()
                
        self.Aset = self.actions()
        self.Sset = self.states() 
        self.Oset = self.observations()

        # CHECKS
        R, T, O = self.R, self.T, self.O
        
        # number of agents
        N = R.shape[0]  
        assert O.shape[0] == N, "Inconsistent number of agents"
        assert len(T.shape[1:-1]) == N, "Inconsistent number of agents"
        assert len(R.shape[2:-1]) == N, "Inconsistent number of agents"
        
        # number of actions for each agent        
        M = T.shape[1] 
        assert np.allclose(T.shape[1:-1], M), 'Inconsistent number of actions'
        assert np.allclose(R.shape[2:-1], M), 'Inconsistent number of actions'
        assert np.all(list(map(len, self.Aset)) == np.array(M).repeat(N)),\
            'Inconsistent number of actions'
            
        # number of states
        Z = T.shape[0] 
        assert T.shape[-1] == Z, 'Inconsistent number of states'
        assert R.shape[-1] == Z, 'Inconsistent number of states'
        assert R.shape[1] == Z, 'Inconsistent number of states'
        assert O.shape[1] == Z, 'Inconsistent number of states'
        assert len(self.Sset) == Z, 'Inconsistent number of states'

        # number of observations
        Q = O.shape[-1]
        assert np.all(list(map(len, self.Oset)) == np.array(Q).repeat(N)),\
            'Inconsistent number of observations'
        
        assert np.allclose(T.sum(-1), 1), 'Transition model wrong'
        assert np.allclose(O.sum(-1), 1), 'Observation model wrong'


# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 22
class SingleAgentUncertainDecisionProblem(ebase):

    def __init__(self, 
                 noiselevel: float, # standard deviation of natural uncertainty
                 probabilityA: float = 0.5, # probability of nature to be in A
                 likelydistance: float = 1): # distance when agent's believe become *very* likely
        self.env_A = probabilityA
        self.noise = noiselevel
        self.likelydistance = likelydistance
        self.probs = probabilities(noiselevel, likelydistance)

        self.N = 1
        self.M = len(self.actions()[0])
        self.Z = len(self.states())
        self.Q = len(self.observations()[0])

        # inital states
        super().__init__()
        # self.state = np.random.choice(np.where(self.F==0)[0])

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 24
@patch
def states(self:SingleAgentUncertainDecisionProblem): 
    return ["A", "B"]

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 26
@patch
def actions(self:SingleAgentUncertainDecisionProblem): 
    return [['A', 'B']]    

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 28
@patch
def observations(self:SingleAgentUncertainDecisionProblem): 
    return [['A', 'a', 'b', 'B']]

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 30
@patch
def TransitionTensor(self:SingleAgentUncertainDecisionProblem):
    dim = np.concatenate(([self.Z],
                          [self.M for _ in range(self.N)],
                          [self.Z]))
    Tsas = np.ones(dim) * (-1)

    for index, _ in np.ndenumerate(Tsas):
        Tsas[index] = self._transition_probability(index[0],
                                                    index[1:-1],
                                                    index[-1])
    return Tsas

@patch
def _transition_probability(self:SingleAgentUncertainDecisionProblem, 
                            s, jA, s_):
        env_ = self.states()[s_]
        if env_ == 'A':
            return self.env_A
        else:
            return 1-self.env_A

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 32
@patch
def RewardTensor(self:SingleAgentUncertainDecisionProblem):
    """Get the Reward Tensor R[i,s,a1,...,aN,s']."""
    dim = np.concatenate(([self.N],
                          [self.Z],
                          [self.M for _ in range(self.N)],
                          [self.Z]))
    Risas = np.zeros(dim)

    for index, _ in np.ndenumerate(Risas):
        Risas[index] = self._reward(index[0], index[1], index[2:-1], index[-1])
    return Risas
    
@patch
def _reward(self:SingleAgentUncertainDecisionProblem, i, s, jA, s_):
        # translating states and actions into coordinates
        env = self.states()[s]
        act = self.actions()[i][jA[0]]
            
        reward = 0.0     
        if env == act: reward = 1.0
        elif env != act: reward = -1.0
        return reward

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 34
@patch
def ObservationTensor(self:SingleAgentUncertainDecisionProblem):
    """Get the Observation Tensor O[i,s,o]."""
    Oiso = np.ones((self.N, self.Z, self.Q))
    
    for index, _ in np.ndenumerate(Oiso):
        Oiso[index] = self._observation(index[0], index[1], index[2])
    return Oiso
    
@patch
def _observation(self:SingleAgentUncertainDecisionProblem, i, s, o):
    # translating states and actions into coordinates    
    env = self.states()[s]
    eobs = self.observations()[i][o]

    # observations probability
    p = 0.0
                    
    if eobs.upper() == env and eobs.isupper():
        p = self.probs[0]
    if eobs.upper() == env and not eobs.isupper():
        p = self.probs[1]
    if eobs.upper() != env and not eobs.isupper():
        p = self.probs[2]
    if eobs.upper() != env and eobs.isupper():
        p = self.probs[3]
        
    return p

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 36
@patch
def id(self:SingleAgentUncertainDecisionProblem):
    """
    Returns id string of environment
    """
    id = f"{self.__class__.__name__}_"+\
        f"{self.noise}_{self.env_A}_{self.likelydistance}"
    return id

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 41
class TwoAgentUncertainDecisionProblem(ebase):

    def __init__(self, 
                 noiselevel: float, # standard deviation of natural uncertainty
                 probabilityA: float = 0.5, # probability of nature to be in A
                 likelydistance: float = 1): # distance when agent's believe become *very* likely
        assert probabilityA >= 0 and probabilityA <= 1 

        self.env_A = probabilityA
        self.noise = noiselevel 
        self.likelydistance = likelydistance
        self.probs = probabilities(noiselevel, likelydistance)
        
        self.N = 2
        self.M = len(self.actions()[0])
        self.Z = len(self.states())
        self.Q = len(self.observations()[0])

        # inital states
        super().__init__()

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 43
@patch
def states(self:TwoAgentUncertainDecisionProblem):
    nAorB = ["A", "B"]  # nature's state
    flow = ['12.', '.1A', '.1B', '21.', '.2A', '.2B']  # social state
    return [f'{n}{f}' for n, f in it.product(nAorB, flow)]

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 45
@patch
def actions(self:TwoAgentUncertainDecisionProblem):
   AorB = ['A', 'B']
   return [AorB, AorB]

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 47
@patch
def observations(self:TwoAgentUncertainDecisionProblem):
    obs = ['A.', 'a.', 'b.', 'B.',  # for the first agent in line
           'AA', 'aA', 'bA', 'BA',  # for the second agent in line      
           'AB', 'aB', 'bB', 'BB', 
           '..']                    # for the inactive agent 
    return [obs, obs]

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 49
@patch
def TransitionTensor(self:TwoAgentUncertainDecisionProblem):
    dim = np.concatenate(([self.Z], [self.M for _ in range(self.N)], [self.Z]))
    Tsas = np.ones(dim) * (-1)

    for index, _ in np.ndenumerate(Tsas):
        Tsas[index] = self._transition(index[0], index[1:-1], index[-1])
    return Tsas
    
@patch
def _transition(self:TwoAgentUncertainDecisionProblem, s, jA, s_):
    # translating states and actions into coordinates
    nat, pos2, pos1, choice = self.states()[s]          # current state  
    nat_, pos2_, pos1_, choice_ = self.states()[s_]     # next state

    # in movement state: 
    #   pos2= agent that plays second, pos1=agent that plays, choise='.'; 
    
    # in final state: 
    #   pos2='.', pos1=agent that plays, choice= choice of previous agent
    
    i = int(pos1)-1  # acting agent                       
    act = self.actions()[i][jA[i]] # action `A` or `B` of acting agent
    
    prop = 0.0  # default probability
    
    if choice != '.' and choice_ == '.':  # "final" states
        if nat_ == 'A':
            prop = self.env_A/2 
            # *1/2 because there are 2 possible next states with nat_='A'
        else:
            prop = (1-self.env_A)/2
                
    elif nat == nat_ and pos2 == pos1_:  # movement
        if act == choice_: prop = 1.0
            
    return prop

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 51
@patch
def RewardTensor(self:TwoAgentUncertainDecisionProblem):
    """Get the Reward Tensor R[i,s,a1,...,aN,s']."""
    dim = np.concatenate(([self.N], [self.Z], [self.M for _ in range(self.N)],
                          [self.Z]))
    Risas = np.zeros(dim)

    for index, _ in np.ndenumerate(Risas):
        Risas[index] = self._reward(index[0], index[1], index[2:-1], index[-1])
    return Risas

@patch
def _reward(self:TwoAgentUncertainDecisionProblem, i, s, jA, s_):
    # translating states and actions into coordinates
    nat, pos2, pos1, choice = self.states()[s]
    nat_, pos2_, pos1_, choice_ = self.states()[s_]
        
    j = int(pos1) - 1  #acting agent
    act = self.actions()[j][jA[j]]  # action `A` or `B` of acting agent           

    reward = 0  # default reward

    if j == i:  # if i is acting agent
        # if act is correct (according to nature)
        if act == nat: reward = 2
        elif act != nat: reward = -2
    return reward 

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 53
@patch
def ObservationTensor(self:TwoAgentUncertainDecisionProblem):
    """Returns Oiso. Probability the agent i makes observation o in state s"""
    Oiso = np.ones((self.N, self.Z, self.Q))
    
    for index, _ in np.ndenumerate(Oiso):
        Oiso[index] = self._observation(index[0], index[1], index[2])
    return Oiso

@patch
def _observation(self:TwoAgentUncertainDecisionProblem, i, s, o):
    # translating states and actions into coordinates       
    nat, _, pos1, choice = self.states()[s]
    nobs, sobs = self.observations()[i][o]  #nature obs., social obs.
              
    # observations probability composed of action obs and env obs
    pA, pE = 0.0, 0.0
        
    if nobs != ".":
        if choice == sobs:   #agent observes the true choice of predecessor
            pA = 1.0      
                
        if int(pos1)-1 == i:  # only pos1 agent observes something
            if nobs.upper() == nat and nobs.isupper():
                pE = self.probs[0]  #prop(A) if env in A, prop(B) if env in B  
            if nobs.upper() == nat and not nobs.isupper():
                pE = self.probs[1]  #prop(a) if env in A, prop(b) if env in B 
            if nobs.upper() != nat and not nobs.isupper():
                pE = self.probs[2]  #prop(b) if env in A, prop(a) if env in B
            if nobs.upper() != nat and nobs.isupper():
                pE = self.probs[3]  #prop(B) if env in A, prop(A) if env in B 
        
    elif nobs == "." and sobs == ".":
        #agent i is not acting agent -> makes no observation
        if int(pos1)-1 != i: pA = pE = 1.0
    
    return pE * pA

# %% ../j01_ENVI_UncertainDecisionProblem.ipynb 55
@patch
def id(self:TwoAgentUncertainDecisionProblem):
        """
        Returns id string of environment
        """
        id = f"{self.__class__.__name__}_"+\
            f"{self.noise}_{self.env_A}_{self.likelydistance}"
        return id
    
